export const astroList = [
  {
    name: "Sergey Ryzhikov",
    flag_image: "./photos/Russia.png",
    profile_image: "./photos/AnatoliIvanishin.jpg",
    description:
      "Sergueï Nikolaïévitch Ryjikov (Сергей Николаевич Рыжиков) (aussi transcrit Ryzhikov) is a Russian cosmonaut ...",
    wiki: "https://en.wikipedia.org/wiki/Sergey_Ryzhikov_(cosmonaut)",
    nationality: "Russian",
    spaceship: "Soyuz MS-17",
    arrival: "21 October 2020",
    departure: "17 April 2021",
  },
  {
    name: "Kate Rubins",
    flag_image: "./photos/Usa.png",
    profile_image: "./photos/KateRubins.jpg",
    description:
      "Kate Rubins is an American microbiologist and NASA astronaut ...",
    wiki: "https://en.wikipedia.org/wiki/Kathleen_Rubins",
    nationality: "American",
    spaceship: "Soyuz MS-17",
    arrival: "21 October 2020",
    departure: "17 April 2021",
  },
  {
    name: "Sergey Kud-Sverchkov",
    flag_image: "./photos/Russia.png",
    profile_image: "./photos/SergeyKudSverchkov.png",
    description:
      "Sergueï Vladimirovitch Koud-Skvertchkov (Сергей Владимирович Кудь-Сверчков) was born on August 23, 1983 at the ...",
    wiki: "https://en.wikipedia.org/wiki/Sergey_Kud-Sverchkov",
    nationality: "Russian",
    spaceship: "Soyuz MS-17",
    arrival: "21 October 2020",
    departure: "17 April 2021",
  },
  {
    name: "Michael Hopkins",
    flag_image: "./photos/Usa.png",
    profile_image: "./photos/MichaelHopkins.jpg",
    description:
      "Michael Scott Hopkins (born December 28, 1968) is a United States Space Force colonel and NASA astronaut ...",
    wiki: "https://en.wikipedia.org/wiki/Michael_S._Hopkins",
    nationality: "American",
    spaceship: "SpaceX Crew-1",
    arrival: "17 November 2020",
    departure: "17 April 2021",
  },
  {
    name: "Victor Glover",
    flag_image: "./photos/Usa.png",
    profile_image: "./photos/VictorGlover.jpg",
    description:
      "Victor Jerome Glover (born April 30, 1976) is a NASA astronaut of the class of 2013 ...",
    wiki: "https://en.wikipedia.org/wiki/Victor_J._Glover",
    nationality: "American",
    spaceship: "SpaceX Crew-1",
    arrival: "17 November 2020",
    departure: "17 April 2021",
  },
  {
    name: "Shannon Walker",
    flag_image: "./photos/Usa.png",
    profile_image: "./photos/ShannonWalker.jpg",
    description:
      "Shannon Walker (born June 4, 1965) is an American physicist and a NASA astronaut selected in 2004 ...",
    wiki: "https://en.wikipedia.org/wiki/Shannon_Walker",
    nationality: "American",
    spaceship: "SpaceX Crew-1",
    arrival: "17 November 2020",
    departure: "17 April 2021",
  },
  {
    name: "Soichi Noguchi",
    flag_image: "./photos/Japan.png",
    profile_image: "./photos/SoichiNoguchi.jpg",
    description:
      "Soichi Noguchi (野口 聡一, Noguchi Sōichi, born 15 April 1965) is a Japanese aeronautical engineer and JAXA astronaut. ...",
    wiki: "https://en.wikipedia.org/wiki/Soichi_Noguchi",
    nationality: "Japan",
    spaceship: "SpaceX Crew-1",
    arrival: "17 November 2020",
    departure: "17 April 2021",
  },
];
